apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: spro-examples-weather-api
spec:
  gateway: kyma-system/kyma-gateway
  hosts: 
    - spro-examples-weather-api
  service:    
    name: spro-examples-weather-api
    namespace: default  
    port: 8080
  rules:
    - path: "/*"
      methods: ["GET", "POST", "DELETE", "PUT", "PATCH", "HEAD"]
      noAuth: true